#钓实体获得该实体刷怪蛋 重要 仅支持具有刷怪蛋的实体 末影龙什么的是没有的~
fishingEntity:
  #世界列表
  world:
    #开关
    type: true
    #概率 50 = 50%
    range: 50
    #可钓的实体 需要在配置文件下面添加实体名字
    entity:
      #格式为 实体ID,money/point/none,数量 设置为none时 不管数量
      - PIG,none,500
fish:
  #世界列表
  world:
    #总开关
    type: true
    #物品ID需大写 若关闭获得物品此项随意写请不要重复
    #格式 物品ID，最小随机数量，最大随机数量，概率
    #当此处的概率未通过则会钓到outMat或者原版的物品
    #满概率 = 100% 概率: 随机挑选其中的物品,然后根据该物品的概率决定是否获得该物品
    mat:
      - DIAMOND,1,3,10%
      - DIRT,1,3,33%
      - STONE,1,3,33%
    #获得到指定mat执行的命令
    matCommand:
      #true = 开 | false = 关
      type: true
      #是否随机执行
      random: ture
      item:
        DIAMOND:
          - say 钻石
          - say 钻石2
        DIRT:
          - say 泥土
          - say 泥土2
        STONE:
          - say 石头
          - say 石头2
    #未通过mat和defaultItem的概率则会钓出来 下面的物品会随机出现一个
    outMat:
      type: true
      item:
        - GLASS,1,3
    #是否可以钓到原版物品 无视mat的概率
    defaultItem:
      type: false
      range: 50%
#message.yml 信息的开关
message:
  #甩杆提示
  fishing: true
  #什么都没钓上来提示
  reelIn: true
  #鱼跑了提示
  failedAttempt: true
  #上钩了提示
  allBite: true